export const ERROR_CODE = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VIDEO_NOT_FOUND: 'VIDEO_NOT_FOUND',
  VIDEO_NOT_READY: 'VIDEO_NOT_READY',
  JOB_ALREADY_QUEUED: 'JOB_ALREADY_QUEUED',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
